### PR TITLE
test_x509: add tzinfo to not_before and not_after datetimes

### PR DESCRIPTION
**Pull request by diabonas**
When using asn1crypto 1.4.0, the unit test fails with the following error message otherwise:
```
ERROR: test_self_sign_certificate (tests.test_x509.X509Tests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/python-pkcs11/src/python-pkcs11-0.7.0/tests/__init__.py", line 95, in wrapper
    return func(self, *args, **kwargs)
  File "/build/python-pkcs11/src/python-pkcs11-0.7.0/tests/test_x509.py", line 186, in test_self_sign_certificate
    'not_before': Time({
  File "/usr/lib/python3.8/site-packages/asn1crypto/core.py", line 1165, in __init__
    raise e
  File "/usr/lib/python3.8/site-packages/asn1crypto/core.py", line 1157, in __init__
    value = spec(value, **params)
  File "/usr/lib/python3.8/site-packages/asn1crypto/core.py", line 1677, in __init__
    raise e
  File "/usr/lib/python3.8/site-packages/asn1crypto/core.py", line 1669, in __init__
    self.set(value)
  File "/usr/lib/python3.8/site-packages/asn1crypto/core.py", line 5008, in set
    raise ValueError('Must be timezone aware')
ValueError: Must be timezone aware
    while constructing asn1crypto.core.UTCTime
    while constructing asn1crypto.x509.Time
```

### CODE REVIEW

**Review by danni — COMMENTED** [review]
This is good. Can you put a matching  `>=` on asn1crypto in the requirements file

**Comment by diabonas** [comment]
> This is good. Can you put a matching `>=` on asn1crypto in the requirements file

Sure, I dug a little deeper and it seems that this requirement was introduced [in asn1crypto 1.0.0](ahttps://github.com/wbond/asn1crypto/commit/c21f024f3834e1f1c00d92daccd71ded31505cc2#diff-d71c6420677feaff153ba18982f3d4fc35dc2bd99d07e3ae561444e56934f6dfR4762-R4763) last year, so I used that as the minimum version.

**Comment by danni** [comment]
Can you also regenerate `requirements.txt` (it's generated via pip-tools, the command line is in the top of the file). I'm not sure it's actually used anywhere (we only use requirements.in via setup.py and dev-requirements.txt) in CI, but it's nice to keep things in sync. Thanks.

**Comment by diabonas** [comment]
Of course, note that my local system is using Python 3.8, which means aenum won't be included in `requirements.txt` any more (it is still in `requirements.in` though).

**Comment by diabonas** [comment]
> which means aenum won't be included in `requirements.txt` any more

Hm, that appears to break CI, so I have manually edited `requirements.txt` to include aenum again.

**Review by danni — APPROVED** [review]

**Comment by danni** [comment]
Thanks!

**Pull request merged**
