### PR TITLE
Extract certificates howto

### PR DESCRIPTION
**Pull request by luisza**
Hi, I spent some time looking how to extract certificates information, so here is a example of how to use this library with PyOpenSSL to extract information and convert to PEM format.

### CODE REVIEW

**Comment by danni** [comment]
You can convert a certificate to PEM format by base64 encoding `VALUE`. Would it help if I made it more clear that `VALUE` contains the certificate?

**Comment by luisza** [comment]
Hi, 

Yes, could be great if you make a clarification on this point.

I have two questions.

1. Strictly, PEM format is not only base64, also have -----BEGIN CERTIFICATE----- and -----END CERTIFICATE----- and is cut on 64 characters per line.

2. Based on VALUE is DER-encoded certificate I could use something like this, for extract certificate information 

```
    from pkcs11.util import x509.decode_x509_certificate
    certs = []
    with token.open() as session:
         for cert in session.get_objects({
                 Attribute.CLASS: ObjectClass.CERTIFICATE}):
              certs.append(decode_x509_certificate(cert[Attribute.VALUE], extended_set=True))
```

but I getting problems with this, see.
error_parsing_certificate


I am working in Costa Rican digital signature software and we use a lot extrancting certificate, so could be great if slots has and funtion to extract all certificates on slot or some utility to that help to extract it pasing a slot object.   I can make a PR with this functionality if you are agree.


Last but not least, You are doing a really great work!.

PD: This is an example of pkcs11 communication for athena smartcard to support personal digital signature software. See [PKCS11PersonClient](https://github.com/luisza/dfva_client/blob/3d7dba8560b483b399e032f760d531ba2bb82e93/client_fva/person.py#L441)

**Comment by danni** [comment]
> Strictly, PEM format is not only base64, also have -----BEGIN CERTIFICATE----- and -----END CERTIFICATE----- and is cut on 64 characters per line.

Yes, but you can use a module like `pem` or `asn1crypto` to handle this.

> Based on VALUE is DER-encoded certificate I could use something like this, for extract certificate information

It looks like your certificates are missing some extensions that the X.509 decoding routine expects to be present. Do you have an example certificate I can use to make this code less brittle? That said, I would use your existing decoding code here, since `decode_x509_certificate` is designed solely to go from DER into PKCS#11 attributes.

I started a branch to port all interchange between PKCS#11 attributes and ASN.1 data structures to use `asn1crypto`, which is a little more obvious to use than `pyasn1`, however it stalled on broken tests.

**Comment by luisza** [comment]
> Yes, but you can use a module like pem or asn1crypto to handle this.

Yea, but documentation needs an example, could be really usefull.

> Do you have an example certificate I can use to make this code less brittle? 

My example certificate is [here](https://github.com/luisza/dfva/blob/79906515e9aace19e2daf6be19c1dbc93deecdea/validator/tests/certificate.py#L1) , this certificate is valid in Costa Rica, and is extracted from PKCS11 device.

**Comment by danni** [comment]
I've included two examples into the documentation. I think in terms of extracting all of the certificates at once, I think the existing generator provides the most flexibility for this.

I'm unsure how much coupling of the `Certificate` object I should add. Should I add an `X509Certificate` object that exposes all of the parsed features, or let people chose the correct library for their need? I'm waiting to be guided by someone who has need of more certificate features than I do (which is none).

**Comment by danni** [comment]
@luisza I've confirmed your certificate definitely breaks my decoder. It doesn't break `asn1crypto`. Can you file this as a new issue?

**Pull request closed without merging**
